[package]
name = "chain-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
anyhow = "1.0"
serde = {version = "1.0", features = ["derive"]}
hex = "0.4"
blake2b_simd = "0.5"
bincode = "1.3"
serde_json = "1.0"
async-trait = "0.1"
rsa = "0.6"
rand = "0.8"
